Update set-mariadb-node

diff --git a/hooks/set-mariadb-node b/hooks/set-mariadb-node
--- a/hooks/set-mariadb-node
+++ b/hooks/set-mariadb-node
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+
+function get_cas_ip {
+   export CAS_IP=`ping -c1 -n $CAS_NAME  | head -n1 | sed "s/.*(\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\)).*/\1/g" `
+ }
+ 
+
 set -e
 
 # Manual Test
@@ -10,3 +16,39 @@ set -e
 #local_gear=$3
  
 echo "$@"  >> $OPENSHIFT_MARIADB_DIR/hook-log
+
+
+CAS_NAME=`cat hook-log | sed "s/'//g" | grep -m 1 -o 'OPENSHIFT_CAS_NODE_FROM_STORAGE=.*' | cut -d '=' -f 2 | cut -d ':' -f 1`
+CAS_PORT=`cat hook-log | sed "s/'//g" | grep -m 1 -o 'OPENSHIFT_CAS_NODE_FROM_STORAGE=.*' | cut -d '=' -f 2 | cut -d ':' -f 2`
+get_cas_ip
+
+grep "scaledb_cas_server_ips *=.*$CAS_IP" ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf &>/dev/null
+if [ $? -ne 0 ];then
+    echo "ip is not in the cas_server_ips list, adding"
+    cas_list=`grep "scaledb_cas_server_ips.*" ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf 2>/dev/null`
+    cas_list="$cas_list,$CAS_IP"
+    sed -i "s/scaledb_cas_server_ips.*/$cas_list/" ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf
+fi
+
+grep "scaledb_cas_server_ips *=.*$CAS_IP" ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf &>/dev/null
+if [ $? -ne 0 ];then
+    echo "ERROR - failed to update scaledb_cas_server_ips"
+    exit 1
+fi
+
+grep "scaledb_cas_server_ports *=.*$CAS_PORT" ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf &>/dev/null
+if [ $? -ne 0 ];then
+    echo "port is not in the cas_server_ports list, adding"
+    cas_list=`grep "scaledb_cas_server_ports.*" ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf 2>/dev/null`
+    cas_list="$cas_list,$CAS_PORT"
+    sed -i "s/scaledb_cas_server_ports.*/$cas_list/" ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf
+fi
+
+grep "scaledb_cas_server_ports *=.*$CAS_PORT" ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf &>/dev/null
+if [ $? -ne 0 ];then
+    echo "ERROR - failed to update scaledb_cas_server_ports"
+    exit 1
+fi
+
+
+
